# Generated by Django 5.2.10 on 2026-01-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_emaildraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('ADS', 'Ads'), ('SCRAPER', 'Scraper'), ('SHEET', 'Google Sheet'), ('MANUAL', 'Manual'), ('WEBHOOK', 'Webhook')], max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadsource'),
        ),
    ]
